name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --production=false
      
  pw:
    name: Run PW
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
      - run: yarn run test:init
      - run: yarn run test:e2e
